[package]
name = "yarn_spinner_gdextension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
csv = "1.4.0"
glob = "0.3.3"
godot = { version = "0.4.2", features = ["experimental-threads"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
yarnspinner = {version = "0.6.3", features = ["serde"] }
rand = "0.10.0-rc.0"
bevy_platform = "0.17.2"
